# -*- coding: utf-8 -*-


from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(733, 590)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 721, 531))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.trainPath = QtGui.QLineEdit(self.tab_1)
        self.trainPath.setGeometry(QtCore.QRect(70, 320, 251, 27))
        self.trainPath.setObjectName(_fromUtf8("trainPath"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 712, 291))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_pitch_median = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_pitch_median.setObjectName(_fromUtf8("checkBox_pitch_median"))
        self.gridLayout.addWidget(self.checkBox_pitch_median, 6, 1, 1, 1)
        self.checkBox_zcr_mean = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_zcr_mean.setObjectName(_fromUtf8("checkBox_zcr_mean"))
        self.gridLayout.addWidget(self.checkBox_zcr_mean, 1, 1, 1, 1)
        self.checkBox_mfcc_var = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_mfcc_var.setObjectName(_fromUtf8("checkBox_mfcc_var"))
        self.gridLayout.addWidget(self.checkBox_mfcc_var, 0, 3, 1, 1)
        self.checkBox_zcr_var = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_zcr_var.setObjectName(_fromUtf8("checkBox_zcr_var"))
        self.gridLayout.addWidget(self.checkBox_zcr_var, 1, 2, 1, 1)
        self.checkBox_pitchsalience = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_pitchsalience.setObjectName(_fromUtf8("checkBox_pitchsalience"))
        self.gridLayout.addWidget(self.checkBox_pitchsalience, 5, 0, 1, 1)
        self.checkBox_lpc_mean = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_lpc_mean.setObjectName(_fromUtf8("checkBox_lpc_mean"))
        self.gridLayout.addWidget(self.checkBox_lpc_mean, 1, 3, 1, 1)
        self.checkBox_mfcc_d1 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_mfcc_d1.setObjectName(_fromUtf8("checkBox_mfcc_d1"))
        self.gridLayout.addWidget(self.checkBox_mfcc_d1, 1, 0, 1, 1)
        self.checkBox_energy_var = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_energy_var.setObjectName(_fromUtf8("checkBox_energy_var"))
        self.gridLayout.addWidget(self.checkBox_energy_var, 2, 2, 1, 1)
        self.checkBox_mfcc_mean = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_mfcc_mean.setObjectName(_fromUtf8("checkBox_mfcc_mean"))
        self.gridLayout.addWidget(self.checkBox_mfcc_mean, 0, 2, 1, 1)
        self.checkBox_pitch_max = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_pitch_max.setObjectName(_fromUtf8("checkBox_pitch_max"))
        self.gridLayout.addWidget(self.checkBox_pitch_max, 5, 1, 1, 1)
        self.checkBox_sharpness_mean = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_sharpness_mean.setObjectName(_fromUtf8("checkBox_sharpness_mean"))
        self.gridLayout.addWidget(self.checkBox_sharpness_mean, 2, 3, 1, 1)
        self.checkBox_beat_median = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_beat_median.setObjectName(_fromUtf8("checkBox_beat_median"))
        self.gridLayout.addWidget(self.checkBox_beat_median, 8, 1, 1, 1)
        self.checkBox_beat_var = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_beat_var.setObjectName(_fromUtf8("checkBox_beat_var"))
        self.gridLayout.addWidget(self.checkBox_beat_var, 8, 0, 1, 1)
        self.checkBox_tuningCents = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_tuningCents.setObjectName(_fromUtf8("checkBox_tuningCents"))
        self.gridLayout.addWidget(self.checkBox_tuningCents, 6, 3, 1, 1)
        self.checkBox_inharmonicity = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_inharmonicity.setObjectName(_fromUtf8("checkBox_inharmonicity"))
        self.gridLayout.addWidget(self.checkBox_inharmonicity, 4, 3, 1, 1)
        self.checkBox_sharpness_var = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_sharpness_var.setObjectName(_fromUtf8("checkBox_sharpness_var"))
        self.gridLayout.addWidget(self.checkBox_sharpness_var, 3, 0, 1, 1)
        self.checkBox_tuningFrequency = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_tuningFrequency.setObjectName(_fromUtf8("checkBox_tuningFrequency"))
        self.gridLayout.addWidget(self.checkBox_tuningFrequency, 6, 2, 1, 1)
        self.checkBox_pitch_var = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_pitch_var.setObjectName(_fromUtf8("checkBox_pitch_var"))
        self.gridLayout.addWidget(self.checkBox_pitch_var, 5, 3, 1, 1)
        self.checkBox_mfcc_median = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_mfcc_median.setObjectName(_fromUtf8("checkBox_mfcc_median"))
        self.gridLayout.addWidget(self.checkBox_mfcc_median, 0, 1, 1, 1)
        self.checkBox_mfcc_max = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_mfcc_max.setObjectName(_fromUtf8("checkBox_mfcc_max"))
        self.gridLayout.addWidget(self.checkBox_mfcc_max, 0, 0, 1, 1)
        self.checkBox_pitch_mean = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_pitch_mean.setObjectName(_fromUtf8("checkBox_pitch_mean"))
        self.gridLayout.addWidget(self.checkBox_pitch_mean, 6, 0, 1, 1)
        self.checkBox_beat_num = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_beat_num.setObjectName(_fromUtf8("checkBox_beat_num"))
        self.gridLayout.addWidget(self.checkBox_beat_num, 7, 0, 1, 1)
        self.checkBox_loudness = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_loudness.setObjectName(_fromUtf8("checkBox_loudness"))
        self.gridLayout.addWidget(self.checkBox_loudness, 4, 2, 1, 1)
        self.checkBox_beat_max = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_beat_max.setObjectName(_fromUtf8("checkBox_beat_max"))
        self.gridLayout.addWidget(self.checkBox_beat_max, 7, 1, 1, 1)
        self.checkBox_energy_mean = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_energy_mean.setObjectName(_fromUtf8("checkBox_energy_mean"))
        self.gridLayout.addWidget(self.checkBox_energy_mean, 2, 1, 1, 1)
        self.checkBox_lsf = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_lsf.setObjectName(_fromUtf8("checkBox_lsf"))
        self.gridLayout.addWidget(self.checkBox_lsf, 3, 1, 1, 1)
        self.checkBox_beat_min = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_beat_min.setObjectName(_fromUtf8("checkBox_beat_min"))
        self.gridLayout.addWidget(self.checkBox_beat_min, 7, 2, 1, 1)
        self.checkBox_pitch_min = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_pitch_min.setObjectName(_fromUtf8("checkBox_pitch_min"))
        self.gridLayout.addWidget(self.checkBox_pitch_min, 5, 2, 1, 1)
        self.checkBox_spFlatness_mean = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_spFlatness_mean.setObjectName(_fromUtf8("checkBox_spFlatness_mean"))
        self.gridLayout.addWidget(self.checkBox_spFlatness_mean, 3, 2, 1, 1)
        self.checkBox_spFlatness_var = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_spFlatness_var.setObjectName(_fromUtf8("checkBox_spFlatness_var"))
        self.gridLayout.addWidget(self.checkBox_spFlatness_var, 3, 3, 1, 1)
        self.checkBox_lpc_var = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_lpc_var.setObjectName(_fromUtf8("checkBox_lpc_var"))
        self.gridLayout.addWidget(self.checkBox_lpc_var, 2, 0, 1, 1)
        self.checkBox_beat_mean = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_beat_mean.setObjectName(_fromUtf8("checkBox_beat_mean"))
        self.gridLayout.addWidget(self.checkBox_beat_mean, 7, 3, 1, 1)
        self.checkBox_spRollOff_mean = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_spRollOff_mean.setObjectName(_fromUtf8("checkBox_spRollOff_mean"))
        self.gridLayout.addWidget(self.checkBox_spRollOff_mean, 4, 0, 1, 1)
        self.checkBox_spRollOff_var = QtGui.QCheckBox(self.gridLayoutWidget)
        self.checkBox_spRollOff_var.setObjectName(_fromUtf8("checkBox_spRollOff_var"))
        self.gridLayout.addWidget(self.checkBox_spRollOff_var, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_1)
        self.label_6.setGeometry(QtCore.QRect(10, 320, 66, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.trainFileButton = QtGui.QToolButton(self.tab_1)
        self.trainFileButton.setGeometry(QtCore.QRect(320, 320, 23, 25))
        self.trainFileButton.setObjectName(_fromUtf8("trainFileButton"))
        self.addTrainPath = QtGui.QPushButton(self.tab_1)
        self.addTrainPath.setGeometry(QtCore.QRect(190, 370, 151, 27))
        self.addTrainPath.setObjectName(_fromUtf8("addTrainPath"))
        self.label_3 = QtGui.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(10, 370, 61, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.trainMode = QtGui.QLineEdit(self.tab_1)
        self.trainMode.setGeometry(QtCore.QRect(70, 370, 113, 27))
        self.trainMode.setObjectName(_fromUtf8("trainMode"))
        self.trainButton = QtGui.QPushButton(self.tab_1)
        self.trainButton.setGeometry(QtCore.QRect(230, 450, 101, 27))
        self.trainButton.setObjectName(_fromUtf8("trainButton"))
        self.groupBox = QtGui.QGroupBox(self.tab_1)
        self.groupBox.setGeometry(QtCore.QRect(350, 300, 361, 191))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.result1 = QtGui.QTextEdit(self.groupBox)
        self.result1.setGeometry(QtCore.QRect(0, 20, 361, 161))
        self.result1.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.result1.setReadOnly(True)
        self.result1.setObjectName(_fromUtf8("result1"))
        self.modeName = QtGui.QLineEdit(self.tab_1)
        self.modeName.setGeometry(QtCore.QRect(70, 420, 113, 27))
        self.modeName.setObjectName(_fromUtf8("modeName"))
        self.label_17 = QtGui.QLabel(self.tab_1)
        self.label_17.setGeometry(QtCore.QRect(10, 420, 61, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.testPath = QtGui.QLineEdit(self.tab)
        self.testPath.setGeometry(QtCore.QRect(110, 40, 251, 27))
        self.testPath.setObjectName(_fromUtf8("testPath"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(40, 40, 66, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.testFileButton = QtGui.QToolButton(self.tab)
        self.testFileButton.setGeometry(QtCore.QRect(370, 40, 23, 25))
        self.testFileButton.setObjectName(_fromUtf8("testFileButton"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(40, 80, 61, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.testMode = QtGui.QLineEdit(self.tab)
        self.testMode.setGeometry(QtCore.QRect(110, 80, 113, 27))
        self.testMode.setObjectName(_fromUtf8("testMode"))
        self.addTestPath = QtGui.QPushButton(self.tab)
        self.addTestPath.setGeometry(QtCore.QRect(240, 80, 151, 27))
        self.addTestPath.setObjectName(_fromUtf8("addTestPath"))
        self.comboBox_model = QtGui.QComboBox(self.tab)
        self.comboBox_model.setGeometry(QtCore.QRect(500, 40, 121, 27))
        self.comboBox_model.setObjectName(_fromUtf8("comboBox_model"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(410, 40, 91, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.testButton = QtGui.QPushButton(self.tab)
        self.testButton.setGeometry(QtCore.QRect(410, 80, 98, 27))
        self.testButton.setObjectName(_fromUtf8("testButton"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(40, 140, 621, 311))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.result4 = QtGui.QTextEdit(self.groupBox_7)
        self.result4.setGeometry(QtCore.QRect(30, 30, 551, 221))
        self.result4.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.result4.setReadOnly(True)
        self.result4.setObjectName(_fromUtf8("result4"))
        self.deleteModelButton = QtGui.QPushButton(self.tab)
        self.deleteModelButton.setGeometry(QtCore.QRect(520, 80, 98, 27))
        self.deleteModelButton.setObjectName(_fromUtf8("deleteModelButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.songPath1 = QtGui.QLineEdit(self.tab_2)
        self.songPath1.setGeometry(QtCore.QRect(120, 40, 291, 27))
        self.songPath1.setObjectName(_fromUtf8("songPath1"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(40, 40, 66, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 31, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.startTestButton = QtGui.QPushButton(self.tab_2)
        self.startTestButton.setGeometry(QtCore.QRect(470, 90, 101, 27))
        self.startTestButton.setObjectName(_fromUtf8("startTestButton"))
        self.tryPlay1 = QtGui.QPushButton(self.tab_2)
        self.tryPlay1.setGeometry(QtCore.QRect(470, 40, 101, 27))
        self.tryPlay1.setObjectName(_fromUtf8("tryPlay1"))
        self.testStyle = QtGui.QComboBox(self.tab_2)
        self.testStyle.setGeometry(QtCore.QRect(120, 90, 111, 27))
        self.testStyle.setObjectName(_fromUtf8("testStyle"))
        self.testStyle.addItem(_fromUtf8(""))
        self.testStyle.addItem(_fromUtf8(""))
        self.testStyle.addItem(_fromUtf8(""))
        self.testStyle.addItem(_fromUtf8(""))
        self.testStyle.addItem(_fromUtf8(""))
        self.testStyle.addItem(_fromUtf8(""))
        self.testStyle.addItem(_fromUtf8(""))
        self.testStyle.addItem(_fromUtf8(""))
        self.testStyle.addItem(_fromUtf8(""))
        self.songFileButton1 = QtGui.QToolButton(self.tab_2)
        self.songFileButton1.setGeometry(QtCore.QRect(410, 40, 23, 25))
        self.songFileButton1.setObjectName(_fromUtf8("songFileButton1"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 150, 621, 311))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.result2 = QtGui.QTextEdit(self.groupBox_2)
        self.result2.setGeometry(QtCore.QRect(30, 30, 551, 221))
        self.result2.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.result2.setReadOnly(True)
        self.result2.setObjectName(_fromUtf8("result2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 66, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.songPath2 = QtGui.QLineEdit(self.tab_3)
        self.songPath2.setGeometry(QtCore.QRect(100, 30, 291, 27))
        self.songPath2.setObjectName(_fromUtf8("songPath2"))
        self.songFileButton2 = QtGui.QToolButton(self.tab_3)
        self.songFileButton2.setGeometry(QtCore.QRect(390, 30, 23, 25))
        self.songFileButton2.setObjectName(_fromUtf8("songFileButton2"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(30, 80, 31, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.featureComboBox = QtGui.QComboBox(self.tab_3)
        self.featureComboBox.setGeometry(QtCore.QRect(100, 80, 121, 27))
        self.featureComboBox.setObjectName(_fromUtf8("featureComboBox"))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.featureComboBox.addItem(_fromUtf8(""))
        self.startEtraButton = QtGui.QPushButton(self.tab_3)
        self.startEtraButton.setGeometry(QtCore.QRect(450, 80, 98, 27))
        self.startEtraButton.setObjectName(_fromUtf8("startEtraButton"))
        self.tryPlay2 = QtGui.QPushButton(self.tab_3)
        self.tryPlay2.setGeometry(QtCore.QRect(450, 30, 98, 27))
        self.tryPlay2.setObjectName(_fromUtf8("tryPlay2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 160, 621, 311))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.result3 = QtGui.QTextEdit(self.groupBox_3)
        self.result3.setGeometry(QtCore.QRect(30, 40, 551, 221))
        self.result3.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.result3.setReadOnly(True)
        self.result3.setObjectName(_fromUtf8("result3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.checkBox_pitch_median.setText(_translate("MainWindow", "pitch中位置", None))
        self.checkBox_zcr_mean.setText(_translate("MainWindow", "zcr平均值", None))
        self.checkBox_mfcc_var.setText(_translate("MainWindow", "mfcc方差", None))
        self.checkBox_zcr_var.setText(_translate("MainWindow", "zcr方差", None))
        self.checkBox_pitchsalience.setText(_translate("MainWindow", "pitchsalience", None))
        self.checkBox_lpc_mean.setText(_translate("MainWindow", "lpc平均值", None))
        self.checkBox_mfcc_d1.setText(_translate("MainWindow", "mfcc_d1最大值", None))
        self.checkBox_energy_var.setText(_translate("MainWindow", "energy方差", None))
        self.checkBox_mfcc_mean.setText(_translate("MainWindow", "mfcc平均值", None))
        self.checkBox_pitch_max.setText(_translate("MainWindow", "pitch最大值", None))
        self.checkBox_sharpness_mean.setText(_translate("MainWindow", "sharpness平均值", None))
        self.checkBox_beat_median.setText(_translate("MainWindow", "beat中位值", None))
        self.checkBox_beat_var.setText(_translate("MainWindow", "beat方差", None))
        self.checkBox_tuningCents.setText(_translate("MainWindow", "tuningCents", None))
        self.checkBox_inharmonicity.setText(_translate("MainWindow", "inharmonicity", None))
        self.checkBox_sharpness_var.setText(_translate("MainWindow", "sharpness方差", None))
        self.checkBox_tuningFrequency.setText(_translate("MainWindow", "tuningFrequency", None))
        self.checkBox_pitch_var.setText(_translate("MainWindow", "pitch方差", None))
        self.checkBox_mfcc_median.setText(_translate("MainWindow", "mfcc中位值", None))
        self.checkBox_mfcc_max.setText(_translate("MainWindow", "mfcc最大值", None))
        self.checkBox_pitch_mean.setText(_translate("MainWindow", "pitch平均数", None))
        self.checkBox_beat_num.setText(_translate("MainWindow", "beat数量", None))
        self.checkBox_loudness.setText(_translate("MainWindow", "loudness", None))
        self.checkBox_beat_max.setText(_translate("MainWindow", "beat最大值", None))
        self.checkBox_energy_mean.setText(_translate("MainWindow", "energy平均值", None))
        self.checkBox_lsf.setText(_translate("MainWindow", "lsf平均值", None))
        self.checkBox_beat_min.setText(_translate("MainWindow", "beat最小值", None))
        self.checkBox_pitch_min.setText(_translate("MainWindow", "pitch最小值", None))
        self.checkBox_spFlatness_mean.setText(_translate("MainWindow", "spectralFlatness平均值", None))
        self.checkBox_spFlatness_var.setText(_translate("MainWindow", "spectralFlatness方差", None))
        self.checkBox_lpc_var.setText(_translate("MainWindow", "lpc方差", None))
        self.checkBox_beat_mean.setText(_translate("MainWindow", "beat平均值", None))
        self.checkBox_spRollOff_mean.setText(_translate("MainWindow", "spectralRollOff平均值", None))
        self.checkBox_spRollOff_var.setText(_translate("MainWindow", "spectralRollOff方差", None))
        self.label_6.setText(_translate("MainWindow", "训练路径", None))
        self.trainFileButton.setText(_translate("MainWindow", "...", None))
        self.addTrainPath.setText(_translate("MainWindow", "添加训练路径和类型", None))
        self.label_3.setText(_translate("MainWindow", "训练类型", None))
        self.trainButton.setText(_translate("MainWindow", "开始训练", None))
        self.groupBox.setTitle(_translate("MainWindow", "测试结果", None))
        self.label_17.setText(_translate("MainWindow", "模型名称", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "训练数据", None))
        self.label_7.setText(_translate("MainWindow", "测试路径", None))
        self.testFileButton.setText(_translate("MainWindow", "...", None))
        self.label_8.setText(_translate("MainWindow", "测试类型", None))
        self.addTestPath.setText(_translate("MainWindow", "添加测试路径和类型", None))
        self.label_18.setText(_translate("MainWindow", "选择测试模型", None))
        self.testButton.setText(_translate("MainWindow", "开始测试", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "测试结果", None))
        self.deleteModelButton.setText(_translate("MainWindow", "删除模型", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "测试数据", None))
        self.label.setText(_translate("MainWindow", "歌曲路径", None))
        self.label_2.setText(_translate("MainWindow", "类型", None))
        self.startTestButton.setText(_translate("MainWindow", "开始测试", None))
        self.tryPlay1.setText(_translate("MainWindow", "试听", None))
        self.testStyle.setItemText(0, _translate("MainWindow", "style", None))
        self.testStyle.setItemText(1, _translate("MainWindow", "mood", None))
        self.testStyle.setItemText(2, _translate("MainWindow", "person", None))
        self.testStyle.setItemText(3, _translate("MainWindow", "classic", None))
        self.testStyle.setItemText(4, _translate("MainWindow", "rock", None))
        self.testStyle.setItemText(5, _translate("MainWindow", "opera", None))
        self.testStyle.setItemText(6, _translate("MainWindow", "jazz", None))
        self.testStyle.setItemText(7, _translate("MainWindow", "happy", None))
        self.testStyle.setItemText(8, _translate("MainWindow", "sad", None))
        self.songFileButton1.setText(_translate("MainWindow", "...", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "测试结果", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "歌曲测试", None))
        self.label_4.setText(_translate("MainWindow", "歌曲路径", None))
        self.songFileButton2.setText(_translate("MainWindow", "...", None))
        self.label_5.setText(_translate("MainWindow", "特征", None))
        self.featureComboBox.setItemText(0, _translate("MainWindow", "mfcc", None))
        self.featureComboBox.setItemText(1, _translate("MainWindow", "mfcc_d1", None))
        self.featureComboBox.setItemText(2, _translate("MainWindow", "zcr", None))
        self.featureComboBox.setItemText(3, _translate("MainWindow", "lpc", None))
        self.featureComboBox.setItemText(4, _translate("MainWindow", "lsf", None))
        self.featureComboBox.setItemText(5, _translate("MainWindow", "sharpness", None))
        self.featureComboBox.setItemText(6, _translate("MainWindow", "spectralFlatness", None))
        self.featureComboBox.setItemText(7, _translate("MainWindow", "spectralRolloff", None))
        self.featureComboBox.setItemText(8, _translate("MainWindow", "energy", None))
        self.featureComboBox.setItemText(9, _translate("MainWindow", "pitch", None))
        self.featureComboBox.setItemText(10, _translate("MainWindow", "beat", None))
        self.startEtraButton.setText(_translate("MainWindow", "开始提取", None))
        self.tryPlay2.setText(_translate("MainWindow", "试听", None))
        self.tryPlay1.setVisible(False)
        self.tryPlay2.setVisible(False)
        self.groupBox_3.setTitle(_translate("MainWindow", "测试结果", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "特征图像", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "其他", None))

